import os
from PIL import Image, ImageDraw, ImageFilter, ImageOps
from pydantic import BaseModel, Field
from google import genai
from google.genai import types

# ---------------------------------------------------------------------------
# Pydantic Schemas for Structured Gemini Outputs
# ---------------------------------------------------------------------------

class Concept(BaseModel):
    headline: str = Field(description="A catchy, highly engaging headline or hook suited for Instagram marketing.")
    visual_description: str = Field(description="A detailed description of the visual scene to be generated by AI.")
    caption: str = Field(description="Recommended marketing caption for the post, including relevant hashtags.")

class ConceptList(BaseModel):
    concepts: list[Concept] = Field(description="A list of exactly 3 distinct marketing concepts.")

# ---------------------------------------------------------------------------
# Background Sizing Utilities
# ---------------------------------------------------------------------------

def get_background_image(bg_path="assets/background.png") -> tuple[Image.Image, int, int]:
    """
    Loads the background image and returns the Image object along with its dimensions.
    Creates a fallback background if the file does not exist.
    """
    if not os.path.exists(bg_path):
        # Create a default 1080x1080 image if it does not exist
        os.makedirs(os.path.dirname(bg_path), exist_ok=True)
        # Create a simple dark elegant placeholder gradient
        img = Image.new("RGB", (1080, 1080), color=(18, 18, 24))
        draw = ImageDraw.Draw(img)
        draw.rectangle([20, 20, 1060, 1060], outline=(212, 175, 55), width=3) # Gold border
        img.save(bg_path, "PNG")
        
    img = Image.open(bg_path).convert("RGBA")
    width, height = img.size
    return img, width, height

# ---------------------------------------------------------------------------
# Gemini API Wrappers
# ---------------------------------------------------------------------------

def get_genai_client(api_key: str = None) -> genai.Client:
    """
    Initializes and returns a GenAI client.
    """
    if api_key:
        return genai.Client(api_key=api_key)
    # Falls back to GEMINI_API_KEY env var
    return genai.Client()

def brainstorm_marketing_concepts(client: genai.Client, purpose: str, user_input: str) -> list[Concept]:
    """
    Uses Gemini to generate 3 highly creative Instagram marketing concepts.
    """
    prompt = f"""
    You are a world-class Instagram Creative Director and Copywriter.
    Generate 3 distinct, highly creative, and engaging marketing concepts for an Instagram post.
    
    Use Case / Purpose: {purpose}
    User Request/Details: {user_input}
    
    For each concept, provide:
    1. A catchy headline or hook.
    2. A detailed visual description of the image to generate. The image should be elegant, professional, and visually stunning.
    3. An engaging caption with hashtags.
    
    Ensure the concepts align perfectly with the selected use case.
    """
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt,
        config=types.GenerateContentConfig(
            response_mime_type="application/json",
            response_schema=ConceptList,
            temperature=0.8,
        )
    )
    
    # Parse output using Pydantic
    try:
        # Gemini python SDK parses the JSON response into the response_schema if possible,
        # otherwise we parse the response.text.
        # Let's handle both cases.
        import json
        data = json.loads(response.text)
        concepts_data = data.get("concepts", [])
        concepts = []
        for c in concepts_data:
            concepts.append(Concept(
                headline=c.get("headline", ""),
                visual_description=c.get("visual_description", ""),
                caption=c.get("caption", "")
            ))
        return concepts
    except Exception as e:
        print(f"Error parsing Gemini response: {e}")
        # Fallback empty list or parse error
        raise ValueError(f"Failed to generate structured concepts: {response.text}")

def expand_concept_prompt(client: genai.Client, purpose: str, concept: Concept, extra_wishes: str = "") -> str:
    """
    Refines and expands a concept description into a highly detailed prompt for Imagen 3.
    """
    prompt = f"""
    You are an expert prompt engineer for Imagen 3.
    Expand the following visual description into a highly detailed prompt for image generation.
    Focus on setting, lighting (e.g., volumetric, cinematic), mood, color scheme, art style (e.g., clean modern digital art, premium corporate 3D render, minimalist flat design), and high-fidelity details.
    
    Category: {purpose}
    Headline Hook: {concept.headline}
    Core Visual Description: {concept.visual_description}
    Extra details: {extra_wishes}
    
    Requirements:
    - Describe a complete, cohesive scene.
    - DO NOT use buzzwords like "photorealistic", "hyperrealistic", "8K". Instead, describe the textures, lighting, and elements in detail.
    - If it's a "Birthday Wish", make sure the scene has a beautiful, elegant background element (like floating gold and cream balloons, confetti, elegant ribbons, or modern geometric frames) with a designated, clean area in the layout to place a person's photo later.
    - Keep the output as just the final image generation prompt text, with no preamble.
    """
    
    response = client.models.generate_content(
        model="gemini-2.5-flash",
        contents=prompt
    )
    return response.text.strip()

def generate_marketing_image_pollinations(prompt: str, aspect_ratio: str = "1:1") -> Image.Image:
    """
    Generates an image for free using Pollinations.ai (Flux model).
    """
    import urllib.parse
    import requests
    from io import BytesIO
    
    ratio_map = {
        "1:1": (1024, 1024),
        "3:4": (768, 1024),
        "4:3": (1024, 768),
        "9:16": (576, 1024),
        "16:9": (1024, 576)
    }
    w, h = ratio_map.get(aspect_ratio, (1024, 1024))
    
    # Truncate prompt to 200 characters to avoid URL length/402/414 limits on the free API
    safe_prompt = prompt[:200] if len(prompt) > 200 else prompt
    encoded_prompt = urllib.parse.quote(safe_prompt)
    
    # Try the newer gen.pollinations.ai endpoint first
    url1 = f"https://gen.pollinations.ai/image/{encoded_prompt}?width={w}&height={h}&nologo=true"
    # Fallback to image.pollinations.ai
    url2 = f"https://image.pollinations.ai/prompt/{encoded_prompt}?width={w}&height={h}&nologo=true"
    
    # Browser-mimicking headers to bypass Cloudflare/CDN rate limiters on shared Streamlit Cloud IPs
    headers = {
        "User-Agent": "Mozilla/5.0 (Macintosh; Intel Mac OS X 10_15_7) AppleWebKit/537.36 (KHTML, like Gecko) Chrome/123.0.0.0 Safari/537.36",
        "Accept": "image/avif,image/webp,image/apng,image/png,image/*,*/*;q=0.8",
        "Accept-Language": "en-US,en;q=0.9",
        "Cache-Control": "no-cache",
        "Connection": "keep-alive"
    }
    
    last_error = None
    for url in [url1, url2]:
        try:
            response = requests.get(url, headers=headers, timeout=40)
            if response.status_code == 200:
                return Image.open(BytesIO(response.content))
            else:
                last_error = f"Status code {response.status_code} from {urllib.parse.urlparse(url).netloc}"
        except Exception as e:
            last_error = str(e)
            
    raise ValueError(f"Pollinations.ai failed: {last_error}. Please try again in a moment.")

def generate_marketing_image(client: genai.Client, prompt: str, aspect_ratio: str = "1:1") -> Image.Image:
    """
    Generates an image using Pollinations AI (completely free open-source Flux model).
    """
    # Map input aspect ratio to allowed formats: "1:1", "3:4", "4:3", "9:16", "16:9"
    allowed_ratios = ["1:1", "3:4", "4:3", "9:16", "16:9"]
    if aspect_ratio not in allowed_ratios:
        aspect_ratio = "1:1"
        
    return generate_marketing_image_pollinations(prompt, aspect_ratio)
    
# ---------------------------------------------------------------------------
# Pillow Image Processing & Layout Merging
# ---------------------------------------------------------------------------

def process_portrait_photo(photo: Image.Image, size=(400, 400), crop_shape="Circle", border_color="#FFD700", border_thickness=5, shadow=True) -> Image.Image:
    """
    Crops and styles the team member's photograph:
    - Resizes it to the target dimensions.
    - Crops it into a Circle or rounded Square.
    - Adds an elegant border.
    - Adds a soft drop shadow.
    """
    # Resize photo to fit
    photo = ImageOps.fit(photo, size, Image.Resampling.LANCZOS).convert("RGBA")
    
    # Create mask
    mask = Image.new("L", size, 0)
    draw_mask = ImageDraw.Draw(mask)
    
    if crop_shape == "Circle":
        draw_mask.ellipse([0, 0, size[0], size[1]], fill=255)
    elif crop_shape == "Rounded Square":
        # 10% corner radius
        radius = int(min(size) * 0.15)
        draw_mask.rounded_rectangle([0, 0, size[0], size[1]], radius=radius, fill=255)
    else: # Square
        draw_mask.rectangle([0, 0, size[0], size[1]], fill=255)
        
    # Apply mask to photo
    styled_photo = Image.new("RGBA", size, (0, 0, 0, 0))
    styled_photo.paste(photo, (0, 0), mask=mask)
    
    # Add border
    # Parse hex color
    hex_color = border_color.lstrip('#')
    rgb_border = tuple(int(hex_color[i:i+2], 16) for i in (0, 2, 4))
    
    border_img = Image.new("RGBA", size, (0, 0, 0, 0))
    draw_border = ImageDraw.Draw(border_img)
    
    # Draw border shape
    half_t = border_thickness / 2
    rect_coords = [half_t, half_t, size[0] - half_t, size[1] - half_t]
    
    if crop_shape == "Circle":
        draw_border.ellipse(rect_coords, outline=rgb_border + (255,), width=border_thickness)
    elif crop_shape == "Rounded Square":
        radius = int(min(size) * 0.15)
        draw_border.rounded_rectangle(rect_coords, radius=radius, outline=rgb_border + (255,), width=border_thickness)
    else: # Square
        draw_border.rectangle(rect_coords, outline=rgb_border + (255,), width=border_thickness)
        
    styled_photo = Image.alpha_composite(styled_photo, border_img)
    
    # Add drop shadow if requested
    if shadow:
        # Create a larger canvas for shadow and offset
        shadow_margin = 20
        shadow_size = (size[0] + shadow_margin * 2, size[1] + shadow_margin * 2)
        shadow_canvas = Image.new("RGBA", shadow_size, (0, 0, 0, 0))
        
        # Create shadow mask (same shape as crop)
        shadow_mask = Image.new("L", size, 0)
        draw_sm = ImageDraw.Draw(shadow_mask)
        if crop_shape == "Circle":
            draw_sm.ellipse([0, 0, size[0], size[1]], fill=120) # 120 opacity for shadow
        elif crop_shape == "Rounded Square":
            radius = int(min(size) * 0.15)
            draw_sm.rounded_rectangle([0, 0, size[0], size[1]], radius=radius, fill=120)
        else:
            draw_sm.rectangle([0, 0, size[0], size[1]], fill=120)
            
        # Paste shadow onto canvas with blur
        shadow_element = Image.new("RGBA", size, (0, 0, 0, 120)) # semi-transparent black
        shadow_canvas.paste(shadow_element, (shadow_margin + 5, shadow_margin + 8), mask=shadow_mask)
        shadow_canvas = shadow_canvas.filter(ImageFilter.GaussianBlur(10))
        
        # Paste the styled photo on top of the shadow canvas
        shadow_canvas.paste(styled_photo, (shadow_margin, shadow_margin), mask=styled_photo.split()[3])
        return shadow_canvas
        
    return styled_photo

def compose_final_marketing_image(
    bg_path: str,
    ai_image: Image.Image,
    composition_style: str = "Overlay AI Image on Background",
    blend_ratio: float = 0.5,
    overlay_photo: Image.Image = None,
    photo_coords: tuple[int, int] = (340, 340), # Default center-ish for 1080x1080
    photo_scale: float = 1.0,
    header_margin: int = 180,
    footer_margin: int = 150,
    side_margin: int = 20
) -> Image.Image:
    """
    Assembles the final graphic:
    - Loads the background image and detects width/height.
    - Programmatically resizes the AI image to fit the background.
    - Blends/Composes the AI image and the background according to composition_style.
    - If overlay_photo is provided, scales and pastes it at photo_coords on the canvas.
    """
    bg_img, bg_w, bg_h = get_background_image(bg_path)
    
    # 1. Resize AI image to fit the background exactly
    ai_resized = ai_image.resize((bg_w, bg_h), Image.Resampling.LANCZOS).convert("RGBA")
    
    # 2. Blend/Composite the background and the AI image
    if composition_style == "Background Frame Overlay":
        # The AI image sits at the bottom, and the background.png template (with logo, borders, etc.) is pasted on top
        # This assumes the background has transparency in its center
        composite = Image.alpha_composite(ai_resized, bg_img)
    elif composition_style == "Blend (Adjustable Opacity)":
        # Standard linear blend of both images
        composite = Image.blend(bg_img, ai_resized, blend_ratio)
    elif composition_style == "AI Image Framed in Center":
        # AI image is placed in the center of the background with a margin
        margin = int(min(bg_w, bg_h) * 0.1) # 10% margin
        ai_w = bg_w - margin * 2
        ai_h = bg_h - margin * 2
        ai_centered = ai_image.resize((ai_w, ai_h), Image.Resampling.LANCZOS).convert("RGBA")
        
        composite = bg_img.copy()
        # Create a subtle drop shadow for the inner frame
        frame_shadow = Image.new("RGBA", (ai_w + 10, ai_h + 10), (0, 0, 0, 100))
        frame_shadow = frame_shadow.filter(ImageFilter.GaussianBlur(8))
        composite.paste(frame_shadow, (margin - 3, margin - 1), mask=frame_shadow.split()[3])
        
        composite.paste(ai_centered, (margin, margin), mask=ai_centered.split()[3])
    elif composition_style == "Fit AI Image in Content Area (Preserve Header/Footer)":
        # AI image is scaled and positioned specifically to sit inside the white space of a letterhead
        ai_w = bg_w - side_margin * 2
        ai_h = bg_h - header_margin - footer_margin
        
        ai_w = max(10, ai_w)
        ai_h = max(10, ai_h)
        
        ai_centered = ai_image.resize((ai_w, ai_h), Image.Resampling.LANCZOS).convert("RGBA")
        
        composite = bg_img.copy()
        composite.paste(ai_centered, (side_margin, header_margin), mask=ai_centered.split()[3])
    else: # "Overlay AI Image on Background"
        # The AI image is overlaid on top of the background.png
        composite = Image.alpha_composite(bg_img, ai_resized)
        
    # 3. If overlay photo is provided (e.g. Birthday Wish), process and apply it
    if overlay_photo is not None:
        # Ensure we work with RGBA
        overlay_photo = overlay_photo.convert("RGBA")
        
        # Scale the photo based on the scale slider
        orig_w, orig_h = overlay_photo.size
        new_w = int(orig_w * photo_scale)
        new_h = int(orig_h * photo_scale)
        
        # Avoid zero or negative sizes
        new_w = max(10, new_w)
        new_h = max(10, new_h)
        
        photo_resized = overlay_photo.resize((new_w, new_h), Image.Resampling.LANCZOS)
        
        # Make a canvas of the same size as the background for drawing/pasting
        canvas = Image.new("RGBA", (bg_w, bg_h), (0, 0, 0, 0))
        
        # To align the photo, we adjust coordinates so photo_coords is the CENTER of the photo
        offset_x = photo_coords[0] - new_w // 2
        offset_y = photo_coords[1] - new_h // 2
        
        canvas.paste(photo_resized, (offset_x, offset_y), mask=photo_resized.split()[3])
        
        # Composite the photo onto the main canvas
        composite = Image.alpha_composite(composite.convert("RGBA"), canvas)
        
    return composite.convert("RGB")
